### ISSUE TITLE
In the "Load a model" section, specifically in the 11th code block, there might be a typo or error

### ISSUE THREAD

**Issue by moslian-off** [VIOLINARTHUR/HKU-DASC7606-A1#1]
The code in the 11th code block is as follows
```python
net = NeuralNet()

def load_model(net, path):
    net.load_state_dict(torch.load(PATH))
    
load_model(net, PATH)
```
The 'PATH' in the function should be in lowercase. Otherwise, an error may occur if this function is used to load models saved with different paths.

**Comment by TianshuoY** [comment]
Yes, you find a typo here. Thank you~
