### ISSUE TITLE
Seems `to(device)` is missing for GPU training imlpementation

### ISSUE THREAD

**Issue by sennett-lau** [VIOLINARTHUR/HKU-DASC7606-A1#2]
In the "Training on GPU?" section, seems the code block has only define the `device`. While even printing it as a `cuda:0`, it does not mean the application trains with GPU. Instead, `to(device)` should be required for saving the  `inputs`, `labels` and network parameters. The necessary modifications are shown below:

For the `train`, `test` and `class_test` function, we should move it to a place after the `device` had been declared, then update the `inputs` and `labels`:
```
def train(...): # also for test and class_test fucntions
  # some code here
  ...
  for data in loader:
    inputs, labels = data
     
    # Add the following line, while use images instead of inputs for test and class_test
    inputs, labels = inputs.to(device), labels.to(device)
    ...
```

When creating a network object:
```
net = ConvolutionNet().to(device)
```

**Comment by TianshuoY** [comment]
Thank you very much for this correction!
