### ISSUE TITLE
Can't have an interactive session

### ISSUE THREAD

**Issue by Aaron020907** [VIOLINARTHUR/HKU-DASC7606-A1#4]
<img width="397" alt="picture" src="https://github.com/user-attachments/assets/a71e6182-2e0c-4675-9a18-da0160cdc973">

**Comment by TianshuoY** [comment]
Please send me more details via HKU email, as well as your attempts to resolve the issue.
For any further inquiries regarding the use of the HKU CS GPU Farm, please use email or the public document.

**Comment by Aaron020907** [comment]
I consulted the technicians and was told that I had written the wrong quotation marks when I modified .bashrc. It has been corrected and I can now enter the interactive GPU.
