### ISSUE TITLE
Questions about assignment submissions

### ISSUE THREAD

**Issue by Aaron020907** [VIOLINARTHUR/HKU-DASC7606-A1#6]
![image](https://github.com/user-attachments/assets/8bc1fd31-67cf-49e2-b8ee-de97fc8b6152)
It is required to submit Assignment1.ipynb, but I am not using jupyternotebook and I have converted the contents of Assignment1.ipynb into a python file. So can I submit the annotated .py file instead of Assignment1.ipynb?

![image](https://github.com/user-attachments/assets/57756cef-c502-4127-a8c4-c2b8af72416e)
For my own net, does the training epoch have to be 5 like the previous two?

I would appreciate it if you could reply early.

**Comment by TianshuoY** [comment]
Q1: Yes you can.
Q2: 5 is just a demonstration, you need to change the epoch number yourself (even in the "previous two").
